### ISSUE TITLE
运行配置，只能使用首次创建的配置，切换配置后保存报错： 运行标签和环境变量不能为空，请设置后再运行

### ISSUE THREAD

**Issue by abeelan** [test-instructor/yangfan#24]
复现步骤：
1. 创建两个环境
2. 创建一个环境变量，分别给两个环境配置上域名
3. 配置管理内创建一个配置，域名写上 ${env_环境变量}
4. 接口管理中，修改环境变量后，点击调试

预期：正常执行，环境切换成功
结果：出现报错：运行标签和环境变量不能为空，请设置后再运行

![image](https://github.com/test-instructor/yangfan/assets/34361264/17a609d6-8331-47b8-8499-090c6c13e7d2)

**Comment by yangfanplatform** [comment]
dev中已修复
