### ISSUE TITLE
项目部署：目前的配置文件有点多，麻烦精简下，各配置文件仅保留一份且放到一块，方便管理

### ISSUE THREAD

**Issue by abeelan** [test-instructor/yangfan#27]
麻烦精简下配置文件，目前是根目录、web、server 都有配置文件，甚至在web目录有 server 的启动脚本；

在docker-compose里面配置文件也太多了，目录有点复杂。

docker-compose 的目的就是串联各服务、依赖项，本不应该这么复杂。

希望配置文件根据服务命名，放在一起就好了

**Comment by yangfanplatform** [comment]
已修复，配置文件调试和docker部署分开成2个文件，
