### ISSUE TITLE
项目部署：配置文件内参数添加注释

### ISSUE THREAD

**Issue by abeelan** [test-instructor/yangfan#28]
服务端配置文件内，是个 gin-vue-admin 官方的默认模板。

放了好多无关的参数。比如七牛、对象存储服务等，这些貌似用不上，不用的干掉，必须的加上注释说明。

配置文件说明：https://www.gin-vue-admin.com/guide/server/config.html#jwt

**Comment by yangfanplatform** [comment]
dev中已修复
