### ISSUE TITLE
期望功能：测试套件内支持复制用例

### ISSUE THREAD

**Issue by abeelan** [test-instructor/yangfan#33]
在下面这种场景下， 比如一个异常接口的参数定义完了，后续的接口就稍微改个字段就行，能复制就好了
![image](https://github.com/test-instructor/yangfan/assets/34361264/2120d422-b306-487e-b6e9-03d6d0e80cba)

目前是重新导入该接口，然后重新编辑字段，稍显麻烦

**Comment by yangfanplatform** [comment]
dev中已修复
