### ISSUE TITLE
部署优化：通过 sh 脚本 + 配置文件的方式，一键部署

### ISSUE THREAD

**Issue by abeelan** [test-instructor/yangfan#35]
预期：

发布一个压缩包，里面有：

- install.sh 
- 配置文件 
- 若干 docker-compose.yml 文件

修改配置文件后，直接执行 sh 脚本就好了

**Comment by test-instructor** [comment]
https://mp.weixin.qq.com/s?__biz=Mzk0MjQ0NjIxNQ==&mid=2247484074&idx=1&sn=7a92a98b761d97cae980805525c1f172&chksm=c2c24142f5b5c854c5282f850e717be15af959f75292b2aa82b7e2289f84cee1c676381f7255#rd

**Comment by test-instructor** [comment]
https://mp.weixin.qq.com/s?__biz=Mzk0MjQ0NjIxNQ==&mid=2247484074&idx=1&sn=7a92a98b761d97cae980805525c1f172&chksm=c2c24142f5b5c854c5282f850e717be15af959f75292b2aa82b7e2289f84cee1c676381f7255#rd
目前已经实现，可以参考这篇文章，或者用以下代码执行即可

```
# 进入目录
mkdir -p /home/yangfan && cd /home/yangfan
# 执行安装
bash -c "$(curl -fsSLk http://docs.yangfan.gd.cn/install/install.sh)"
```
